name: Devious Eye Entertainment
favicon: null
layout_spectrum: 0.06052479986101389
typography_spectrum: 0.0787455237004906
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7479609975125641
  lightness: 0.40955149102956057
  saturation: 0.8407584228552878
  rhythmicContrast: 0.02964709117077291
purpose: []
