name: Moba Strike
favicon: null
layout_spectrum: 1
typography_spectrum: 0.63504
title: Moba Strike - Original Moba Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00b354'
    - '#ffffff'
    - '#72ff00'
    - '#a1b095'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
